############################################################
# Root workflow for building
############################################################
name: Build

run-name: Build ${{github.run_id}}

on: [push, workflow_dispatch]

jobs:
  # Create install media
  create-install-media:
    runs-on: windows-2022
    timeout-minutes: 60
    steps:
      # Check out
      - name: Checkout
        uses: actions/checkout@v4

      # Determine cache keys
      - name: Get cache keys
        id: get-cache-keys
        shell: pwsh
        run: |
          ## Get cache key for downloads cache
          $cacheKeys = ./build/github_build_helper.ps1 -GetInstallMediaCacheKeys -DownloadsCsvFile ./install-media/downloads.csv -ScriptFile ./install-media/create_install_image.ps1
          echo $cacheKeys
          echo "install-files-cache-key=$($cacheKeys.installFilesKey)" >> $env:GITHUB_OUTPUT
          echo "install-image-cache-key=$($cacheKeys.installImageKey)" >> $env:GITHUB_OUTPUT

      # Get cached install image
      - name: Get cached install image
        id: get-cached-install-image
        uses: actions/cache@v3
        with:
          key: install-image-${{steps.get-cache-keys.outputs.install-image-cache-key}}
          path: ./install-media/install.iso

      # Get cached install files
      - name: Get cached install files
        id: get-cached-install-files
        if: steps.get-cached-install-image.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          key: install-files-${{steps.get-cache-keys.outputs.install-files-cache-key}}
          restore-keys: install-files-
          path: ./install-media/downloads

      # Download install files
      - name: Download install files
        id: download-install-files
        if: (steps.get-cached-install-image.outputs.cache-hit != 'true') && (steps.get-cached-install-files.outputs.cache-hit != 'true')
        shell: pwsh
        run: ./install-media/download_install_files.ps1 -DownloadsCsvFile ./install-media/downloads.csv -OutputDir ./install-media/downloads -CleanupDownloads

      # Verify install files
      - name: Verify install files
        id: verify-install-files
        if: (steps.get-cached-install-image.outputs.cache-hit != 'true') && (steps.get-cached-install-files.outputs.cache-hit == 'true')
        shell: pwsh
        run: ./install-media/download_install_files.ps1 -DownloadsCsvFile ./install-media/downloads.csv -OutputDir ./install-media/downloads -VerifyOnly

      # Install Windows ADK deployment tools
      - name: Install Windows ADK deployment tools
        if: steps.get-cached-install-image.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          ./build/github_build_helper.ps1 -InstallAdkDeploymentTools || throw "Error installing ADK deployment tools"
          echo "Adding Oscdimg dir to PATH"
          echo "${env:ProgramFiles(x86)}\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\Oscdimg" >> $env:GITHUB_PATH

      # Create install image
      - name: Create install image
        if: steps.get-cached-install-image.outputs.cache-hit != 'true'
        shell: pwsh
        run: ./install-media/create_install_image.ps1 -InstallFilesDir ./install-media/downloads -WorkDir ./install-media/work -Output ./install-media/install.iso

      # Upload custom install image artifact
      - name: Upload install image
        uses: actions/upload-artifact@v4
        with:
          name: install-media
          path: ./install-media/install.iso
          retention-days: 5

  # Build and test Vagrant box
  build-and-test:
    # Run after cache-install-media
    needs: create-install-media

    # Build using different virtualization providers
    strategy:
      fail-fast: false
      matrix:
        include:
          - virt-provider-name: virtualbox
            virt-provider-id: vbx
          - virt-provider-name: vmware
            virt-provider-id: vmw

    # Reference reusable workflow to do the actual building and testing
    uses: ./.github/workflows/sub-build-and-test.yml

    # Inherit secrets
    secrets: inherit

    # Pass parameters to the sub-workflow
    with:
      # Virtualization provider name
      virt-provider-name: ${{matrix.virt-provider-name}}
      # Virtualization provider ID
      virt-provider-id: ${{matrix.virt-provider-id}}


  # Rerun failed jobs
  #rerun-failed-jobs:
  #  runs-on: ubuntu-latest
  #  needs: build-and-test
  #  if: failure()
  #  steps:
  #    # Check out
  #    - name: Checkout
  #      uses: actions/checkout@v4

  #    # Rerun failed jobs
  #    - name: Rerun failed jobs in the current workflow
  #      env:
  #        GH_TOKEN: ${{ github.token }}
  #      run: gh run rerun ${{ github.run_id }} --failed