############################################################
# Root workflow for building
############################################################
name: Ubuntu-Test

run-name: Ubuntu-Test ${{github.run_id}}

on: [workflow_dispatch]

jobs:
  # Test
  test:
    runs-on: ubuntu-latest-m
    steps:
      # Check out
      - name: Checkout
        uses: actions/checkout@v4

      # Setup build environment
      - name: Setup build environment
        run: |
          bash ./build/github_build_helper.sh install-build-tools vmw ${{runner.os}} build
          sudo apt-install foot
          sudo apt-install waypipe

      # Setup tmate session
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
